# Generated by Django 5.0.3 on 2024-03-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('ownerName', models.CharField(max_length=50)),
                ('rollNo', models.IntegerField()),
                ('ownerEmail', models.EmailField(max_length=254, unique=True)),
                ('clientId', models.CharField(max_length=20, unique=True)),
                ('clientSecret', models.CharField(max_length=40)),
            ],
        ),
    ]
