# Generated by Django 5.0.3 on 2024-03-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('discount', models.IntegerField(default=0)),
                ('availability', models.CharField(default='out-of-stock', max_length=15)),
            ],
        ),
    ]
